### ISSUE TITLE
Consistency with team-member titles

### ISSUE THREAD

**Issue by ddorinson** [BayAreaMetro/fast-trips-project#1]
# First GH issue!!  Starting out small...

Comparing titles for Dave & Diana, I see differences in:
Format: "title1 and title2" versus "title1 (title2)"
Tone: "serious and silly" versus "silly (serious)"

Not sure if these are intentional?  I think the format for Dave is preferable.

**Comment by e-lo** [comment]
Fixed. See https://github.com/e-lo/fast-trips-project/commit/637c4a1d0d011892a8085b6f7b240ffe92baf415
