### ISSUE TITLE
Text style for image titles/credits?

### ISSUE THREAD

**Issue by ddorinson** [BayAreaMetro/fast-trips-project#10]
Looking at the "Updated Workplan" post, I find it hard to distinguish the name & credit info for the images from the surrounding text, because it is the same size, font, and style as the prose content.  Can we change this--maybe use a sans serif or at least italics?

**Comment by e-lo** [comment]
Fixed: https://github.com/e-lo/fast-trips-project/commit/e816d93e39c4c99db129ebfba645c5fb4208edb7
