### ISSUE TITLE
Change Billy's title

### ISSUE THREAD

**Issue by billyc** [BayAreaMetro/fast-trips-project#11]
I'm now the "Director of Data".

:-D

**Comment by e-lo** [comment]
yeah- awesome!
Fixed: https://github.com/e-lo/fast-trips-project/commit/7b80b04c3a8c5c53f41286c21b0490c9c01e7594  and https://github.com/e-lo/fast-trips-project/commit/9c6e5ce4a63ed17942f7597bf6ec7d7378eb37a6
