### ISSUE TITLE
Fix website tagline grammar

### ISSUE THREAD

**Issue by billyc** [BayAreaMetro/fast-trips-project#12]
Sorry to nitpick but it's literally the first sentence on the webpage.

_We are three public agencies, working together, to try and create better tools to analyze human-scale travel in congested, urban cities_

sounds a lot better as

_We are three public agencies, working together, trying to create better tools for analyzing human-scale travel in congested, urban cities_

**Comment by e-lo** [comment]
Please do nitpick - it is hard to read things "for real" when you have seen them forever.  My guess is that I was having a "real world" moment.  

Changed here: https://github.com/e-lo/fast-trips-project/commit/654597e7690fa4fc892602d6c3a3e0e7218cd9ec

**Comment by billyc** [comment]
I wasn't worried. Easy enough to fix. Oh look!  You already fixed. :-)
