### ISSUE TITLE
Typos/layout on latest blog post (01-Jun-2015)

### ISSUE THREAD

**Issue by ddorinson** [BayAreaMetro/fast-trips-project#18]
FYI, there is a stray "s" on its own line above "how is that different" in section 2. Detailed representation of Individuals...

Also, in general, can we provide a little more white-space between graphics and subsequent text?  Right now it's very crowded, particularly for the section headers.  Maybe this is an attribute of Jekyll...?  Hope it's not too hard to adjust.

**Comment by e-lo** [comment]
Fixed: https://github.com/MetropolitanTransportationCommission/fast-trips-project/commit/061e43d856336cc9ff59726337585d00764d279f
