### ISSUE TITLE
Consider re-naming QPR 'seasons'?

### ISSUE THREAD

**Issue by ddorinson** [BayAreaMetro/fast-trips-project#24]
Was just looking through old QPRs on this site, and noticed that somehow we skipped "Summer" in 2015.  We submit reports in Jan(1) / Apr(4) / Jul(7) / Oct(10).  The Library listing goes from "Spring 2015," which links to the 2015-07 PDF, to "Fall 2015," which links to the 2015-10 file, oops!  To clean-up, we can choose to re-name from the first going forward or working backwards from the most recent.  Happy to implement if you let me know which you think makes more sense.

**Comment by ddorinson** [comment]
One further wrinkle...  I see that we have our grant application and progress reports listed in two places on the site: at the top of both the 'Meta' and 'Library' pages.  The season names are the same in both places, so we still have that hiccup between Spring 2015 and later quarters.  (Also, on the Meta page, the Fall 2015 report is not shown at all).  So, whatever we decide for Library, we can fix here, too.  Or, we can delete the listing on Meta and just keep everything on Library to avoid duplication/mismatch issues.

**Comment by e-lo** [comment]
@ddorinson  - renamed the April 2015 report to Spring in both places.  Took <60 seconds.

See: 5aaf318cde6bd78eed56109c3b3315b3ad368c89
