### ISSUE TITLE
Move Calib Plan PDF to public location?

### ISSUE THREAD

**Issue by ddorinson** [BayAreaMetro/fast-trips-project#25]
In the TRL section of the Library page, clicking on "Calibration Plan" asks you to sign-in to Box, but we should store the file (currently here: [https://app.box.com/file/95315576529]) in a publicly accessible location.  I'm happy to execute the change, but not sure whether it's better to move it to the PUBLIC folder on Box vs. putting it here on the website repo (similar to [http://fast-trips.mtc.ca.gov/library/ResearchTrack-PublicWorkplan.pdf]).  Let me know if you have a logic to which docs live in each place.

**Comment by e-lo** [comment]
Hmm - when i look at that link (https://app.box.com/file/95315576529) it seems to both be in the public folder and be accessible w/out signing into box.  Maybe it was a different file?

I think in general we would prefer the docs being on Box.

**Comment by ddorinson** [comment]
You're right, it shows up in PUBLIC for me as well!  I know at least one of the links hit the sign-in screen, but I've clicked around some more and can't find anything else amiss, so nevermind!  :P
