### ISSUE TITLE
Confusing text layout/styles on "References" page

### ISSUE THREAD

**Issue by ddorinson** [BayAreaMetro/fast-trips-project#4]
I find the look and feel of this page a little bit awkward, particularly the text under the sub-heading "REFERENCES."  This content could be referring to 1, 2, or 3 different documents, depending on how you are meant to interpret the use of italics, the presence/lack of hyperlink, etc.  I am not sure if this is due to Jekyll behavior, intended design, or just quirkiness...?  Should we use bullets/numbering/indents to set off individual entries?  

(And if we do choose some kind of numbering: does it make sense to use a disciplined approach here to support any academic citations needed in future research papers?)

**Comment by e-lo** [comment]
Fixed: https://github.com/e-lo/fast-trips-project/commit/dd3f84ecef1ed6334e902cdd9fa670b88b30cc62
