### ISSUE TITLE
Documents vs. References?

### ISSUE THREAD

**Issue by ddorinson** [BayAreaMetro/fast-trips-project#5]
Just curious if there is any reason to distinguish the documents that we produce from external references produced by others?  Later on, we'll have lots more entries under Deliverables and Progress Reports, and we may end up grouping them into separate homes, so it seems useful to think about this now.

**Comment by e-lo** [comment]
I don't have strong feelings here other than that we shouldn't overthink it.

Here's a straw man proposal:
- Put technical deliverables with the technical tasks (which might eventually have their own pages)
- Put progress reports, grant application, etc on the meta page
- Put all deliverables and reports on the References Page (maybe rename it to...??)
- remove external references from the references page and put them in the appropriate technical tasks.

**Comment by e-lo** [comment]
Fixed: https://github.com/e-lo/fast-trips-project/commit/dd3f84ecef1ed6334e902cdd9fa670b88b30cc62
