### ISSUE TITLE
Link to other C10 projects...or at least grantees?

### ISSUE THREAD

**Issue by ddorinson** [BayAreaMetro/fast-trips-project#6]
This is probably more of a reminder for later than anything that needs to be resolved now...

It sounds like other C10 grantees are not making a big effort on communications & outreach at this stage, but if they do build any web content, we should link to it in the text under "FUNDING PROGRAM" on the "META" page.  

In the meantime, is it worth linking to the grantee agencies?  Maybe one or more has a press release or a page about their travel modeling team or something?

**Comment by e-lo** [comment]
I cannot find any other websites with info on what they are doing but happy to post if they exist.

**Comment by ddorinson** [comment]
Figured as much.  Why don't we close the Github issue for now, and maybe put a tickler task on Asana to check on the other C10 recipients towards the end of the year...?
