### ISSUE TITLE
Odd text wrapping on blog posts

### ISSUE THREAD

**Issue by ddorinson** [BayAreaMetro/fast-trips-project#7]
I am not sure if this is the same as "Fix blog alignment" in the ReadMe... and I don't know if it's driven by a design choice or a site behavior issue.

Looking at the post called "Measuring Ourselves", I find it hard to see the "Metrics" after each "Goal."  Part of the confusion is that some goals have multiple metrics, which we bullet, but then goals with single metrics get list in the shuffle when they just continue on the same line.  I wonder if there is a simple formatting convention that would help?  Could we do some kind of two-column layout ,or is that too complex?

**Comment by e-lo** [comment]
Fixed: https://github.com/e-lo/fast-trips-project/commit/de3a8b3fcd0238cc4ab0e8fb6091e4c3b8b6c322
