### ISSUE TITLE
Check blog post headings

### ISSUE THREAD

**Issue by ddorinson** [BayAreaMetro/fast-trips-project#8]
The font sizes look mis-matched on some of the blog posts.  
-- In "Measuring Ourselves" the text for "Capacity building and partnerships" is larger than the other two categories of metrics ("Tool implementation and deployment" and "Technology transfer / research dissemination").  
-- In "Working together through bureaucratic fences", the first sub-heading is smaller than all of the others.

It looks like this happens because they were assigned different heading levels, which is probably not what you intended.

**Comment by e-lo** [comment]
Fixed in https://github.com/e-lo/fast-trips-project/commit/d0ca90a44c1f4d71f2c3fe817ab83d0affbac39f
